# Generated by Django 2.2.5 on 2019-11-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rides',
            field=models.ManyToManyField(blank=True, db_index=True, to='rides.Ride'),
        ),
    ]
