# Generated by Django 2.2.5 on 2019-10-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='seats_available',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
