# Generated by Django 2.2.5 on 2019-10-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20191014_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='departure_date',
            field=models.DateField(),
        ),
    ]