# Generated by Django 2.2.5 on 2019-10-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_auto_20191014_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_state',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='ride',
            name='origin_state',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]