# Generated by Django 2.2.5 on 2019-10-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_auto_20191021_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='seats_available',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]