# Generated by Django 2.2.5 on 2019-12-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_auto_20191130_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
