# Generated by Django 2.2.5 on 2019-11-11 21:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='passenger_list',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
