# Generated by Django 2.2.5 on 2019-11-11 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0009_ride_passenger_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passenger_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
