# Generated by Django 2.2.5 on 2019-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_auto_20191111_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='asking_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
