# Generated by Django 2.2.5 on 2019-11-13 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_auto_20191113_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
